### ISSUE TITLE
change id of time

### ISSUE THREAD

**Issue by tikismoke** [XavierBerger/Solar-Router-for-ESPHome#17]
https://github.com/XavierBerger/Solar-Router-for-ESPHome/blob/22c3912fd9d19e2ae506fbb93b6e8a1131450b1b/solar_router/energy_saved_counter_theorical.yaml#L40

A lot of user use talready this id in common packages (with wifi and other stuff).
Just rename the id to avoid duplicate and compilation issue please.

something like:

```
# Enable time component to reset energy at midnight
time:
  - platform: homeassistant
    id: homeassistant_time_for_solar_router
```
