### ISSUE TITLE
Using the DS18B20 temperature sensor

### ISSUE THREAD

**Issue by dloriot** [XavierBerger/Solar-Router-for-ESPHome#19]
I would like to add the DS18B20 temperature sensor to cut off the relay when a certain temperature is reached.

 arduino framework : 

```
one_wire:
  - platform: gpio
    pin: GPIO13
    id: dallas_d7

sensor:
  - platform: dallas_temp
    address: 0x0000000000000000
    one_wire_id: dallas_d7
    name: temperature
    update_interval: 30s
```

esp-idf framework :

```
external_components:
  - source: github://nrandell/dallasng

dallasng:
  - pin: GPIO13
    update_interval: 10s

sensor:
  - platform: dallasng
    name: Temperature
    id: temperature_sensor
    index: 0
    resolution: 12
    filters:
      - filter_out: NAN
```

<img width="783" alt="image" src="https://github.com/XavierBerger/Solar-Router-for-ESPHome/assets/11027381/d0f0a211-a76a-4d4b-ab6a-860f47fb8017">

<img width="825" alt="image" src="https://github.com/XavierBerger/Solar-Router-for-ESPHome/assets/11027381/e657351d-df12-44d4-8e3f-dce3c2e665e9">
