### ISSUE TITLE
Temperature Sensor  substitution in case of Dallas Sensor

### ISSUE THREAD

**Issue by Chilgl0rd** [XavierBerger/Solar-Router-for-ESPHome#52]
Salut Xavier,

Jespère que tu vas bien.
J'ai installé une DS18B20. Lorsque je déclare le 1Wire + Sensor + Substitution la remperature remonte bien dans ta variable safety_temperature

one_wire:
  - platform: gpio
    pin: GPIO32
    id: BUS1

sensor:
  - platform: dallas_temp
    name: "Temperature"
    update_interval: 120s
    one_wire_id: BUS1

...

  # Temperature sensor
  temperature_sensor: sensor.lctsr02_temperature

Par contre il me semble que ca ne déclenche pas  Safety limit reached

Il faut passer à la place par ça ? Et pas besoin de faire les déclarations 1 Wire et Sensor ?

 # Sensor in home assistant gathering the temperature
  DS18B20_pin: GPIO32
# Safety limit LED configuration
  red_led_inverted: "False"
  temperature_update_interval: 60s

Mais quid de la substitution temperature_sensor ? Ca n'est pas très clair dans ta doc ;-)

Merci :-)
Xtof

**Comment by XavierBerger** [comment]
Bonjour, 
J'avoue que je ne comprends pas bien ce que tu essayes  de faire. 
Soit, tu utilises le package pour le DS18B20 et tu rajoutes le paramètre définissant `DS18B20_pin` dans substitution. 
Soit, tu utilises le package Home Assistant et là, il faut définir la paramètre `temperature_sensor` dans substitution.
En aucun cas les 2.
Les paramètres de la LED sont optionnels, c'est juste pour avoir un retour sur le routeur.

Voici par exemple la configuration du routeur solaire que je suis en train de mettre en place pour mon chauffe-eau :

```yaml
substitutions:
  # Power meter source 
  # Define ip address of Power Meter (Fronius Inverter)
  power_meter_ip_address: "192.168.1.21"

  # Regulator configuration 
  # Define GPIO pin connected to AC Dimmer for gate and zero crossing detection.
  regulator_gate_pin: GPIO17
  regulator_zero_crossing_pin: GPIO39

  # LEDs 
  # Green LED is reflecting regulation status
  # Yellow LED is reflecting power meter status
  # Ted LED reflecting safety limit
  green_led_pin: GPIO32
  yellow_led_pin: GPIO14
  red_led_pin: GPIO4

  # Temperature sensor
  DS18B20_pin: GPIO02
  temperature_update_interval: 1s


packages:
  power_meter:
    url: https://github.com/XavierBerger/Solar-Router-for-ESPHome/
    file: solar_router/power_meter_fronius.yaml
    refresh: 1d
  regulator:
    url: https://github.com/XavierBerger/Solar-Router-for-ESPHome/
    file: solar_router/regulator_triac.yaml
    refresh: 1d
  engine:
    url: https://github.com/XavierBerger/Solar-Router-for-ESPHome/
    file: solar_router/engine.yaml
    refresh: 1d
  energy_counter:
    url: https://github.com/XavierBerger/Solar-Router-for-ESPHome/
    file: solar_router/energy_counter_theorical.yaml
    refresh: 1d
  temperature_limiter:
    url: https://github.com/XavierBerger/Solar-Router-for-ESPHome/
    file: solar_router/temperature_limiter_DS18B20.yaml
    refresh: 1d
```
