### ISSUE TITLE
Doc update: Schedule (de)activation of load

### ISSUE THREAD

**Issue by ghisch** [XavierBerger/Solar-Router-for-ESPHome#60]
Hello

I want to switch on the load (regulator at 100 for example) at fixed & pre-defined schedules. The goal is to force activation of the water-heater at night. Of course you can have HomeAssistant turn on the switch with an automation, but in case of a wifi outage, it's not going to happens, and I don't want (no one wants) cold water shower. So it would be nice to be able to define schedules to activate and deactivate the load.

I was about to ask for a new feature request but realized this could be done in the config of ESPHome with the time component with something like this:

```
time:
  - platform: sntp
    on_time:
      - seconds: 0
        minutes: 0
        hours: 2
        then:
          - switch.turn_on: regulator_id
```

So I think it would be nice to have such thing in the doc :)

Thanks

**Comment by XavierBerger** [comment]
Hello, 

Yes, I think it could be good to add such a thing in the doc. 
Did you already test it? 
Because, at first look, I think that it may work or may have a conflict with the regulation. 
Also, you should think to turn it OFF ... or let the regulation manage the relay again.
I think that the idea to have it as a module is also a good one, since it will be possible to configure it inside Home Assistant (and maybe add automation to update this scheddule). But this could come in a second time.
I let you propose a PR, and I will give you my feedback.

Thanks for this proposal.

**Comment by ghisch** [comment]
Update: When this [PR](https://github.com/XavierBerger/Solar-Router-for-ESPHome/pull/66) will be merged, scheduling (de)activation of load(s) will be as easy as

```yaml
time:
  - platform: sntp
    on_time:
      # Disable Router then set router level to 100
      - seconds: 0
        minutes: */5
        hours: 0-1
        then:
          - switch.turn_off: activate
          - number.set:
              id: router_level
              value: 100
      # Set router level to 0 then re-enable Router then
      - seconds: 0
        minutes: 0
        hours: 2
        then:
          - number.set:
              id: router_level
              value: 0
          - switch.turn_on: activate
```

This config will work with any current router engines (`engine`, `engine_on_off`) and any future engines.

PS: To make really sure the load is enabled, I made it so that the router_level is set to 100 every 5 min from 00:00 to 1:55 included.

**Comment by SullyP** [comment]
Hello,

After some try to make it configurable (even if on_time hours/minutes are not templatable 😣), i proposed someting like that:

scheduler_no_routing_percent_power.yaml (open to idea for the yaml name)
```
substitutions:
  scheduler_unique_id: "Default"


number:
  # Scheduler Router level from 0 to 100
  # When solar routing is disabled at scheduled time: Acts as a manual control to set the router level
  - platform: template
    name: "${scheduler_unique_id} Scheduler Router Level"
    id: "${scheduler_unique_id}_scheduler_router_level"
    min_value: 0
    max_value: 100
    initial_value: 100
    step: 1
    unit_of_measurement: "%"
    optimistic: True
    mode: slider

text:
  # Begin HH:MM of the scheduler (MM need to be a multiple of 5 minutes)
  - platform: template
    name: "${scheduler_unique_id} Scheduler Begin Hour Minute"
    id: "${scheduler_unique_id}_scheduler_begin_hour_min"
    optimistic: True
    min_length: 5
    max_length: 5
    mode: text
    initial_value: "00:00"
  # End HH:MM of the scheduler (MM need to be a multiple of 5 minutes)
  - platform: template
    name: "${scheduler_unique_id} Scheduler End Hour Minute"
    id: "${scheduler_unique_id}_scheduler_end_hour_min"
    optimistic: True
    min_length: 5
    max_length: 5
    mode: text
    initial_value: "02:00"

time:
  - platform: sntp
    id: ${scheduler_unique_id}_sntp
    on_time:
      
      - seconds: 0
        minutes: /5
        then:
        # If Now is equal to Begin HH:MM of the scheduler
        - if:
            condition:
              lambda: return id(${scheduler_unique_id}_scheduler_begin_hour_min).state == id(${scheduler_unique_id}_sntp).now().strftime("%H:%M");
            then:
              # Disable Router then set router level to X percent
              - switch.turn_off: activate
              - number.set:
                  id: router_level
                  value: !lambda return id(${scheduler_unique_id}_scheduler_router_level).state;
            else:
              # If Now is equal to End HH:MM of the scheduler
              - if:
                  condition:
                    lambda: return id(${scheduler_unique_id}_scheduler_end_hour_min).state == id(${scheduler_unique_id}_sntp).now().strftime("%H:%M");
                  then:
                    # Set router level to 0 then Enable router
                    - number.set:
                        id: router_level
                        value: 0
                    - switch.turn_on: activate
```

_scheduler_unique_id_ allow to import multiple time the same package file to do different schedule time.

Maybe i can make initial_value init with some substitution too ?

If this idea seems good i will create a PR with documentation.
